[mypy]
python_version = 3.11
strict = True
plugins = pydantic.mypy
files = src/jev_reactor
warn_unused_ignores = True

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True

[mypy-typesafe_sdk.*]
ignore_missing_imports = True
