"""Export built-in packs as YAML. The Python definition is the source of truth."""

from __future__ import annotations

from pathlib import Path

from jev_reactor.errors import PackError
from jev_reactor.packs import BUILTIN_PACKS

HEADER = """\
# Generated by `jev-reactor export-pack {name}`. Do not edit in place.
# The Python definition in jev_reactor/packs/ is the source of truth; a test fails if this
# file drifts from it. To make your own pack, copy this file, change its `id`, edit the
# questions, then run `jev-reactor validate-pack <file>`.
#
# Thresholds below are documented starting points, not calibrated values. Calibrate them
# on your own traces (see docs/policy-writing.md).
"""


def export_yaml(name: str) -> str:
    try:
        pack = BUILTIN_PACKS[name]()
    except KeyError:
        raise PackError(
            f"unknown built-in pack {name!r}; choose from {', '.join(sorted(BUILTIN_PACKS))}"
        ) from None
    return pack.to_yaml(HEADER.format(name=name))


def export_all(directory: str | Path) -> list[Path]:
    out = Path(directory)
    out.mkdir(parents=True, exist_ok=True)
    written = []
    for name in BUILTIN_PACKS:
        path = out / f"{name}.yaml"
        path.write_text(export_yaml(name), encoding="utf-8", newline="\n")
        written.append(path)
    return written
